# spring:
#  datasource:
#   url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

# jpa:
#  hibernate:
#      ddl-auto: create-drop
#   properties:
#     hibernate:
#      dialect: org.hibernate.dialect.H2Dialect
spring:
  application:
    name: libflow-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bibliotecadb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # 1. CONFIGURAÇÃO DO FLYWAY
  flyway:
    enabled: true
    # Garanta que seus arquivos estejam em: src/main/resources/db/migration
    locations: classpath:db/migration
    baseline-on-migrate: true
    # Adicionado para garantir que o Flyway limpe erros de tentativas falhas em dev
    repair-on-migrate: true

  jpa:
    # 2. HIBERNATE VALIDATE
    # Usamos 'validate' para garantir que o Java bate com o SQL do Flyway
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Garante que o Hibernate aguarde o Flyway completar as migrações
        migration:
          strategy: flyway
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /docs
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: true
