
    spring:
      datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password:

      jpa:
        hibernate:
          ddl-auto: create-drop
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect

    springdoc:
      # Altera o caminho da interface visual (ex: http://localhost:8080/docs)
      swagger-ui:
        path: /docs
        # Ordena os endpoints por ordem alfabética ou por tag
        operations-sorter: alpha
        tags-sorter: alpha
      # Altera o caminho do JSON técnico da API
      api-docs:
        path: /v3/api-docs
      # Mostra o tempo de resposta das requisições no Swagger
      show-actuator: true



    #spring:
    #  application:
    #    name: libflow-api
    #
    #  datasource:
    #    # Substitua 'localhost:5432/bibliotecadb' pelo seu IP e nome do banco real
    #    url: jdbc:postgresql://localhost:5432/bibliotecadb
    #    username: postgres
    #    password: sua_senha_aqui
    #    driver-class-name: org.postgresql.Driver
    #
    #  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #    hibernate:
    #      # 'update' cria/altera as tabelas automaticamente no Postgres
    #      ddl-auto: update
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    #        # Necessário para o Postgres em algumas versões
    #        jdbc:
    #          lob:
    #            non_contextual_creation: true
    #
    #  flyway:
    #    enabled: false

